POST http://localhost:5000/requests
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "items": [
    "{{$uuid}}",
    "{{$uuid}}",
    "{{$uuid}}",
    "{{$uuid}}",
    "{{$uuid}}"
  ]
}

> {% client.global.set("request_id", response.body.toString()); %}

###

GET http://localhost:5000/requests/{{request_id}}/status